export const categories = [
  { name: 'FRUTAS' },
  { name: 'VERDURAS' },
  { name: 'SECOS' },
  { name: 'LACTEOS' },
  { name: 'CONGELADOS' },
  { name: 'DULCES Y BOTANA' },
  { name: 'ABARROTE' },
  { name: 'LIMPIEZA' },
  { name: 'DESECHABLE' },
  { name: 'PESCADOS Y MARISCOS' },
  { name: 'RES Y CERDO' },
  { name: 'POLLO' },
  { name: 'PAN' },
  { name: 'TORTILLA' },
  { name: 'BEBIDAS' },
  { name: 'VARIOS' },
]
