export enum Resources {
  PRODUCT = 'PRODUCT',
  CATEGORY = 'CATEGORY',
  BRANCH = 'BRANCH',
  BRAND = 'BRAND',
  INVOICE = 'INVOICE',
  PROVIDER = 'PROVIDER',
  ORDER = 'ORDER',
  ORDER_ITEM = 'ORDER_ITEM',
}
