export * from '@modules/product/dtos/create-product-price.dto'
export * from '@modules/product/dtos/create-product.dto'
export * from '@modules/product/dtos/update-product-price.dto'
export * from '@modules/product/dtos/update-product.dto'
export * from '@modules/product/dtos/relations-product.dto'
